### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by nagyattis81** [hzdgopher/64klang#1]
Dear Dominik,

I tried to compile the 64klang, but unfortunatelly it did not work.

Compile log:
1>------ Build started: Project: Player, Configuration: Release Win32 ------
1>SynthNode.cpp
1>c:\git\64klang\player\player\synthnode.cpp(3636): error C2664: 'sample_t Sampler_Sample(SynthNode *,sample_t &)': cannot convert argument 2 from 'sample_t' to 'sample_t &'
1>c:\git\64klang\player\player\synthnode.cpp(3636): note: A non-const reference may only be bound to an lvalue
1>c:\git\64klang\player\player\synthnode.cpp(4800): error C2664: 'sample_t Sampler_Sample(SynthNode *,sample_t &)': cannot convert argument 2 from 'sample_t' to 'sample_t &'
1>c:\git\64klang\player\player\synthnode.cpp(4800): note: A non-const reference may only be bound to an lvalue
1>c:\git\64klang\player\player\synthnode.cpp(4801): error C2664: 'sample_t Sampler_Sample(SynthNode *,sample_t &)': cannot convert argument 2 from 'sample_t' to 'sample_t &'
1>c:\git\64klang\player\player\synthnode.cpp(4801): note: A non-const reference may only be bound to an lvalue
1>c:\git\64klang\player\player\synthnode.cpp(5162): error C2362: initialization of 'info' is skipped by 'goto CreateNodes_ReturnExisting'
1>c:\git\64klang\player\player\synthnode.cpp(5139): note: see declaration of 'info'
1>c:\git\64klang\player\player\synthnode.cpp(5162): note: see declaration of 'CreateNodes_ReturnExisting'
1>c:\git\64klang\player\player\synthnode.cpp(5162): error C2362: initialization of 'values' is skipped by 'goto CreateNodes_ReturnExisting'
1>c:\git\64klang\player\player\synthnode.cpp(5138): note: see declaration of 'values'
1>c:\git\64klang\player\player\synthnode.cpp(5162): note: see declaration of 'CreateNodes_ReturnExisting'
1>Done building project "Player.vcxproj" -- FAILED.

Microsoft Visual Studio Community 2017
Version 15.6.2
Windows SDK version: 10.0.16299.0
Platform Toolset: Visual Studio 2017 (v141)

Kind regards,
aha

**Comment by hzdgopher** [comment]
should be fixed, compiles here now with the mentioned compiler/toolset combination.
update and try again please

**Comment by nagyattis81** [comment]
Dear Dominik,

Your fix works well, the example program works too. Thank you for your help.

Kind regards,
aha
